spring:
  application:
    name: ms-product
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ms_product
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 20s
          max-attempts: 3
          max-interval: 30s
          multiplier: 1
        missing-queues-fatal: false
rabbitmq:
  queue:
    order-service:
      queue: ORDER_Q
      queue_dlq: ORDER_DLQ
    rating-service:
      queue: RATING_Q
      queue_dlq: RATING_DLQ
    subscription-service:
      queue: SUBSCRIPTION_Q
      queue_dlq: SUBSCRIPTION_DLQ
redis:
  server:
    urls: redis://localhost:6379
ms:
  auth:
    url: http://localhost:8383
